// <auto-generated />
using System;
using EventTracker.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventTracker.DataContext.Migrations
{
    [DbContext(typeof(EventTrackerContext))]
    partial class EventTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventTracker.Model.EventModel", b =>
                {
                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "guid");

                    b.Property<int?>("CurrentParticipants")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "current_participants");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "max_participants");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("PrizePool")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "prize_pool");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Sponsors")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "sponsors");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("StreamingUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "streaming_url");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.HasKey("Guid");

                    b.HasIndex("LocationId");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("ec4d0e5a-d7df-43d7-b974-48f9e876a516"),
                            Date = new DateTime(2025, 1, 9, 15, 11, 33, 184, DateTimeKind.Local).AddTicks(9897),
                            Description = "Une compétition intergalactique époustouflante où les meilleurs s'affrontent pour dominer l'univers.",
                            LocationId = 1,
                            Name = "Star Reign Championship",
                            PrizePool = "100,000 EUR",
                            Slug = "star-reign-championship",
                            Sponsors = "[\"Red Bull\",\"Alienware\",\"Logitech\"]",
                            Status = "Open",
                            StreamingUrl = "https://twitch.tv/star_reign_championship",
                            Tags = "[\"eSport\",\"Galactic\",\"Star Reign\"]"
                        },
                        new
                        {
                            Guid = new Guid("3e8607f7-1c1e-4824-955e-c27b088e95cd"),
                            Date = new DateTime(2025, 2, 9, 15, 11, 33, 184, DateTimeKind.Local).AddTicks(9975),
                            Description = "La finale du tournoi mondial de League of Legends, un rendez-vous incontournable pour les fans d'eSport.",
                            LocationId = 2,
                            Name = "League of Legends Finals",
                            PrizePool = "500,000 EUR",
                            Slug = "league-of-legends-finals",
                            Sponsors = "[\"Riot Games\",\"Corsair\",\"SteelSeries\"]",
                            Status = "Open",
                            StreamingUrl = "https://twitch.tv/lol_worlds",
                            Tags = "[\"eSport\",\"League of Legends\",\"Worlds\"]"
                        });
                });

            modelBuilder.Entity("EventTracker.Model.LocationModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "address");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "capacity");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "city");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "postalcode");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ZAC du Cornillon Nord",
                            Capacity = 80000,
                            City = "Saint-Denis",
                            Name = "Stade de France",
                            PostalCode = "93216"
                        },
                        new
                        {
                            Id = 2,
                            Address = "8 Boulevard de Bercy",
                            Capacity = 20000,
                            City = "Paris",
                            Name = "Accor Arena",
                            PostalCode = "75012"
                        },
                        new
                        {
                            Id = 3,
                            Address = "20 Place des Docteurs Mérieux",
                            Capacity = 17000,
                            City = "Lyon",
                            Name = "Halle Tony Garnier",
                            PostalCode = "69007"
                        });
                });

            modelBuilder.Entity("EventTracker.Model.EventModel", b =>
                {
                    b.HasOne("EventTracker.Model.LocationModel", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EventTracker.Model.LocationModel", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
